410 file analytics
scientist-softserv/palni-palci pull request #477
Opened 2023-05-16 19:57 UTC by alishaevn

# Story
- ref #410 

We needed to change the method to reference a class that exists, ensuring that the class gets required.

Legato dynamically creates methods based on classes/modules that extend it’s model.  And depending on the load sequence of classes, these dynamic methods can vary. By adding an explicit require, we ensure that those methods are properly defined on the profile.

# Expected Behavior Before Changes
trying to view the analytics for a file would fail

# Expected Behavior After Changes
we can view file analytics

# Screenshots / Video
![image](https://github.com/scientist-softserv/palni-palci/assets/29032869/29c8b1b7-30c3-4b39-8c43-0c59ad9993a1)

# resources
- https://github.com/tpitale/legato/blob/master/lib/legato/profile_methods.rb#L17-L19
- https://github.com/samvera/hyrax/issues/5955

2023-05-16 20:18 UTC, alishaevn commented
@orangewolf @jeremyf and I would like your feedback on the solution here. it incorporates the changes from [hyrax#5958](https://github.com/samvera/hyrax/pull/5958), but the code still failed without the `require` statements because the `Legato::ProfileMethods.instance_methods` weren't finding `hyrax__pageviews` or `hyrax__downloads`.

do you have a better solution?

2023-05-16 21:36 UTC, orangewolf requested changes

2023-05-16 21:36 UTC, orangewolf commented on app/models/file_download_stat_decorator.rb
> +require 'hyrax/download'
I _think_ you want this to require_dependency here https://apidock.com/rails/ActiveSupport/Dependencies/Loadable/require_dependency

2023-05-17 00:26 UTC, alishaevn commented
rob and I paired on the refactor. merging.

2023-05-17 13:14 UTC, merged