695-update-resource-allocations
scientist-softserv/palni-palci pull request #535
Opened 2023-06-05 19:05 UTC by aprilrieger

Refs https://github.com/scientist-softserv/dev-ops/issues/695

Please read the initial issue linked above

2023-06-06 04:25 UTC, orangewolf commented on ops/production-deploy.tmpl.yaml
> -    memory: "4Gi"
this should be 2/4GB like other web processes. I can understand matching UTK, but we're not importing massively here so I think the worker can be much smaller as well

2023-06-06 04:26 UTC, orangewolf requested changes
I think pals prod can be a lot smaller

2023-06-06 16:19 UTC, aprilrieger commented
@orangewolf I updated the values, let me know if these work.

2023-06-07 17:04 UTC, orangewolf approved these changes
looks great!

2023-06-07 17:05 UTC, merged