🐛 Ensure Hyku's view_path is first in list
scientist-softserv/palni-palci pull request #735
Opened 2023-08-22 20:02 UTC by jeremyf

Prior to this commit, and with three engines (e.g. Bulkrax, Hyrax::DOI,
and AllinsonFlex), we had a situation in which the first view path may
not have been the application.  The consequence being that the view
lookup would potentially behave in unexpected ways.

Below is the commit message on the patches submitted for the three
engines.  The message further details the problem:

> Prior to this commit, the logic for finding the Hyrax in the view path
> was assuming a version number (e.g. `hyrax-2.`); however if the we
> pinned Hyrax to a branch/sha then we might have `hyrax-a`.  The result
> being that we pre-prended the view path into the application.  That
> created the conditions where the `view_paths` first element might not
> have been the application but instead a gem/engine.
>
> Which means that the convention of overriding views in the application
> would not work.
>
> With this commit, we're using the Hyrax's engine's root to determine
> the view path suffix.  Further, if Hyrax is not in the view path, we
> don't again inject at the beginning of the list the Bulkrax engine
> into the view path.

Related to:

- https://github.com/scientist-softserv/palni-palci/pull/731
- https://github.com/samvera-labs/bulkrax/pull/855
- https://github.com/samvera-labs/allinson_flex/pull/122
- https://github.com/samvera-labs/bulkrax/pull/855

2023-08-22 20:22 UTC, jeremyf commented
Note: there are places in the application that prepend to a view_path; that prepending happens in sub-classes and is thus isolated to those instances.

2023-08-22 21:15 UTC, aprilrieger approved these changes

2023-08-22 22:01 UTC, alishaevn requested changes

2023-08-22 22:01 UTC, alishaevn commented on config/application.rb
> +      # - https://github.com/samvera-labs/bulkrax/pull/855
```suggestion
```

2023-08-23 01:17 UTC, alishaevn approved these changes
still would like my suggestion to be applied, but I won't have you wait for me coming back again to approve it.

2023-08-23 14:17 UTC, merged