Fixing reshare some more
scientist-softserv/palni-palci pull request #959
Opened 2024-01-11 07:57 UTC by orangewolf

# Story

There are issues with reshare. If a url is opened from an email or directly pasted in to the URL bar, it works fine, but if it is from a clicked link on a web page it will not work. 

# Expected Behavior Before Changes
Going to http://old.notch8.com/test.html and clicking either test link will take you through Reshare login (see 1password) and then to an error page on the reshare side.

# Expected Behavior After Changes
Going to http://old.notch8.com/test.html and clicking either test link will take you through Reshare login (see 1password) and then to our side where the work loads.

2024-01-11 08:07 UTC, orangewolf commented
@jeremyf I ended up moving to cookies because the session kept getting dropped. while I was at it, I simplified things to be more devise/omniauth typical. This is going up to prod because the reshare folks are getting frustrated but still needs review and merge and all that jazz

2024-01-13 03:33 UTC, jeremyf approved these changes

2024-01-16 14:12 UTC, jeremyf requested changes

2024-01-16 14:12 UTC, jeremyf commented on app/controllers/application_controller.rb
> -    def authenticate_if_needed
There remains a `before_action :authenticate_if_needed` declaration on line 21.  Yet we're removing this method.  Which should it be?  My understanding is that without this in place, the staging environment will no longer require HTTP Auth.

2024-01-16 19:35 UTC, jeremyf approved these changes

2024-01-16 19:36 UTC, merged